global:
  name: consul

server:
  storage: 2Gi # Dev uses lower storage

ui:
  enabled: true
  ingress:
    enabled: false
    ingressClassName: public
    pathType: Prefix
    hosts:
      - host: dev-consul.naim.run
        paths:
          - /
